on: [push, pull_request]

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 aarch64
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            echo "Trying the bazel binary"
            
            sudo apt install curl -y
            curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=1Vz5cWhNtGMYL8qHFJ5jgWUYVG-QNOJVY" > /dev/null
            CODE="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"
            curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${CODE}&id=1Vz5cWhNtGMYL8qHFJ5jgWUYVG-QNOJVY" -o bazel
            sudo chmod +x bazel
            sudo cp ./bazel /usr/local/bin
            bazel --help
            rm ./bazel

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
